config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "organisations#index"
  devise_for :users
  resources :organisations, except: %i[new] do
    resources :employments, only: %i[create]
    resources :shifts, only: %i[create]
  end
  resources :employments, only: %i[destroy]
  resources :shifts, only: %i[update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :user
  belongs_to :organisation

  validates :user_id, uniqueness: { scope: :organisation_id }
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users, through: :employments
  has_many :employments
  has_many :shifts

  validates :name, :hourly_rate, presence: true
  validates :name, length: { in: 2..64 }, uniqueness: true
  validates :hourly_rate, numericality: { greater_than: 0.0, less_than: 100.01 }
end

app/models/shift.rb
class Shift < ApplicationRecord
  attribute :start_date, :date
  attribute :start_time, :datetime

  belongs_to :user
  belongs_to :organisation

  validates :start, :finish, :break, presence: true

  def hours
    (self.finish - self.start - (self.break * 60)) / 3600
  end

  def sunday_hours
    @finish_without_break = Time.parse(self.finish.to_s) - (self.break * 60)
    if self.start.wday == 0 && @finish_without_break.wday == 0
      return self.hours
    elsif self.start.wday == 0 && @finish_without_break.wday == 1
      return (@finish_without_break - self.start.end_of_day) / 3600
    elsif self.start.wday == 6 && @finish_without_break.wday == 0
      return (@finish_without_break.midnight - self.start) / 3600
    else
      return 0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shifts
  has_many :employments
  has_many :organisations, through: :employments

  validates :full_name, format: { with: /\A([a-z]+[ \-.,']*)+\z/i }, length: { in: 2..64 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
  end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  def create
    @organisation = Organisation.find(params[:organisation_id])
    @employment = Employment.new(user: current_user, organisation: @organisation)
    if @employment.save
      redirect_to organisations_path, notice: "You have successfully joined an organisation."
    else
      render "organisations/index"
    end
  end

  def destroy
    @employment = Employment.find(params[:id])
    if @employment.destroy
      redirect_to organisations_path, notice: "You have successfully left an organisation."
    else
      render "organisation/index"
    end
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :find_organisation, only: %i[show edit update destroy]

  def index
    @organisations = Organisation.all
    @organisation = Organisation.new
  end

  def show
    @employments = Employment.where(organisation: @organisation)
    @shifts = Shift.where(organisation: @organisation).order(start: :desc)
    @shift = Shift.new

    # Date filter params
    if params[:start_date].present? || params[:finish_date].present?
      @start_date = params[:start_date].empty? ? "1970-01-01" : params[:start_date]
      @finish_date = params[:finish_date].empty? ? Date.today.strftime("%Y-%m-%d") : params[:finish_date]
      @shifts = @shifts
                  .where(start: @start_date..@finish_date)
                  .where(finish: @start_date..@finish_date)
    end

    # Employee search params
    if params[:query].present?
      @shifts = @shifts.where(user: User.where('full_name ILIKE ?', "%#{params[:query]}%"))
    end

    # Table sort params
    if params[:sort].present? && params[:order].present?
      @shifts = Shift.where(organisation: @organisation).order("#{params[:sort]} #{params[:order]}")
    end
    
    respond_to do |format|
      format.html
      format.text { render partial: 'shifts.html', locals: { shifts: @shifts } }
    end
  end

  def create
    @organisation = Organisation.new(organisation_params)
    respond_to do |format|
      if @organisation.save
        format.html { redirect_to organisations_path, notice: 'Organisation was successfully created' }
        format.json
      else
        @organisations = Organisation.all
        format.html { render :index }
        format.json
      end
    end
  end

  def edit; end

  def update
    if @organisation.update(organisation_params)
      redirect_to organisations_path, notice: 'Organisation was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @employments = Employment.where(organisation: @organisation)
    @employments.each { |employment| employment.destroy }
    @shifts = Shift.where(organisation: @organisation)
    @shifts.each { |shift| shift.destroy }
    if @organisation.delete
      redirect_to organisations_path, notice: 'Organisation was successfully deleted'
    else
      redirect_to edit_organisation(@organisation), notice: 'Unable to delete organisation'
    end
  end

  private

  def find_organisation
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:name, :hourly_rate)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :find_organisation, except: %i[update destroy]
  before_action :get_shifts, :get_employments, except: %i[destroy]
  before_action :find_shift, only: %i[update destroy]

  def create
    @shift = Shift.new(shift_params)
    @shift.user = current_user
    @shift.organisation = @organisation
    respond_to do |format|
      if @shift.save
        format.html { redirect_to @organisation, notice: 'Shift was successfully created' }
        format.json
      else
        @shift = Organisation.all
        format.html { render organisations_path }
        format.json
      end
    end
  end

  def update
    @organisation = @shift.organisation
    if @shift.update(shift_params)
      redirect_to @organisation, notice: 'Shift was successfully updated'
    else
      render :index
    end
  end

  def destroy
    @organisation = @shift.organisation
    if @shift.delete
      redirect_to @organisation, notice: 'Shift was successfully deleted'
    else
      redirect_to @organisation, notice: 'Unable to delete shift'
    end
  end

  private

  def find_organisation
    @organisation = Organisation.find(params[:organisation_id])
  end
  
  def get_shifts
    @shifts = Shift.where(organisation: @organisation).order(start: :desc)
  end
  
  def get_employments
    @employments = Employment.where(organisation: @organisation)
  end

  def find_shift
    @shift = Shift.find(params[:id])
  end

  def shift_params
    @shift_params = params.require(:shift).permit(:start_date, :start_time, :finish, :break)
    
    # Calculate start time from virtual attributes
    @shift_params[:start] = DateTime.parse("#{@shift_params[:start_date]} #{@shift_params[:start_time]}")
    
    # Calculate overnight shift from virtual attributes
    if @shift_params[:start_time] >= @shift_params[:finish]
      @shift_params[:finish] = DateTime.parse("#{(Date.parse(@shift_params[:start_date]) + 1).to_s} #{@shift_params[:finish]}")
    else
      @shift_params[:finish] = DateTime.parse("#{@shift_params[:start_date]} #{@shift_params[:finish]}")
    end
    
    @shift_params
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flex--main">
      <%= render "shared/navbar" %>
      <main class="flex--start-ver">
        <div class="container">
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/organisations/_organisations.html.erb
<% @employment = Employment.find_by(user: current_user, organisation: organisation) %>
<li>
  <%= organisation.name %> 
  <%= link_to "Edit", edit_organisation_path(organisation) %> 
  <% if @employment %>
    <%= link_to "Shifts", organisation %>
    <%= link_to "Leave", employment_path(@employment), method: :delete %>
  <% else %>
    <%= link_to "Join", organisation_employments_path(organisation), method: :post %>
  <% end %>
</li>

app/views/organisations/_shift.html.erb
<% if employments.find_by(user: shift.user) %>
  <div class="tr" data-current="false" data-rowid="<%= shift.id %>">
<% else %>
  <div class="tr" style="display:none;" data-current="true" data-rowid="<%= shift.id %>">
<% end %>
    <div class="td"><%= shift.user.full_name %></div>
    <div class="td"><%= shift.start.strftime("%d/%m/%Y")%></div>
    <div class="td"><%= shift.start.strftime("%H:%M") %></div>
    <div class="td"><%= shift.finish.strftime("%H:%M") %></div>
    <div class="td"><%= shift.break %></div>
    <div class="td"><%= "%.2f" % shift.hours %></div>
    <div class="td">£<%= "%.2f" % ((shift.hours - shift.sunday_hours) * @organisation.hourly_rate + (shift.sunday_hours * @organisation.hourly_rate * 2)) %></div>
<% if employments.find_by(user: shift.user) %>
    <div class="td">
      <%= link_to "Edit", organisation_shifts_path(@organisation), data: { id: shift.id, action: "click->shifts#showForm" } %>
      <%= link_to "Delete", shift, method: :delete %>
    </div>
  </div>
  <%= form_for shift, html: { class: "tr", style: "display:none;", data: { formid: shift.id } } do |f| %>
    <div class="td"><%= current_user.full_name %></div>
    <div class="td"><%= f.date_field :start_date, form: "edit_shift_#{shift.id}", value: Date.parse(shift.start.to_s) %></div>
    <div class="td"><%= f.time_field :start_time, form: "edit_shift_#{shift.id}", value: (Time.parse(shift.start.to_s)).strftime("%T.%L") %></div>
    <div class="td"><%= f.time_field :finish, form: "edit_shift_#{shift.id}" %></div>
    <div class="td"><%= f.number_field :break, step: 1, form: "edit_shift_#{shift.id}" %></div>
    <div class="td"><%= f.submit form: "edit_shift_#{shift.id}", data: { action: "submit->shifts#updateShift" } %></div>
    <div class="td"></div>
    <div class="td"><%= link_to "Cancel", organisation_shifts_path(@organisation), data: { id: shift.id, action: "click->shifts#hideForm" } %></div>
  <% end %>
<% else %>
    <div class="td">
    </div>
  </div>
<% end %>

app/views/organisations/_shifts.html.erb
<% shifts.each do |shift| %>
  <%= render "organisations/shift.html.erb", shift: shift, employments: @employments %>
<% end %>

app/views/organisations/edit.html.erb
<h2>Edit Organisation</h2>
<%= form_for @organisation do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hourly_rate %><br />
    <%= f.number_field :hourly_rate, in: 0.01..100.00, step: 0.01 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to "Delete", organisation_path(@organisation), method: :delete %>

app/views/organisations/index.html.erb
<div data-controller="organisations">
  <h2>Organisations</h2>
  <% if @organisations.length > 0 %>
    <ul data-organisations-target="list">
      <% @organisations.each do |organisation| %>
        <%= render "organisations", organisation: organisation %>
      <% end %>
    </ul>
  <% else %>
    <p>There are no organisations.</p>
    <p>Create a new one using the form below.</p>
  <% end %>

  <h2>Create Organisation</h2>
  <%= form_for @organisation, data: { organisations_target: "form" }, remote: true do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :hourly_rate %><br />
      <%= f.number_field :hourly_rate, step: 0.01 %>
    </div>
    <div class="actions">
      <%= f.submit data: { action: "submit->organisations#submit" } %>
    </div>
  <% end %>
</div>

app/views/organisations/show.html.erb
<h2><%= @organisation.name %></h2>
<h3>Shifts</h3>
<div data-controller="shifts">

  <div class="section">
    <p>Search for an employee: </p>
    <%= form_tag @organisation, method: :get, data: { shifts_target: "searchForm" } do %>
      <div class="field">
        <%= text_field_tag :query, params[:query], placeholder: "Employee name", data: { action: "input->shifts#search", shifts_target: "input" } %>
      </div>
    <% end %>
  </div>

  <div class="section">
    <p>Filter by date range: </p>
    <%= form_tag @organisation, method: :get, id: "filter_shift", data: { shifts_target: "form" } do %>
      <div class="field">
        <%= date_field_tag :start_date, params[:start_date], form: "filter_shift", data: { shifts_target: "startDate" } %>
      </div>
      <div class="field">
        <%= date_field_tag :finish_date, params[:finish_date], form: "filter_shift", data: { shifts_target: "finishDate" } %>
      </div>
      <div class="actions">
        <%= button_tag "Filter Dates", type: "submit", form: "filter_shift", data: { action: "click->shifts#filterDate" } %>
      </div>
    <% end %>
    <div class="actions">
      <%= button_tag "Clear Date", data: { action: "click->shifts#clearDate" } %>
    </div>
  </div>

  <div class="section">
    <%= link_to "Current Employees", @organisation, data: { action: "click->shifts#showCurrent" } %>
    <%= link_to "Previous Employees", @organisation, data: { action: "click->shifts#showPrevious" } %>
  </div>

  <div class="table">
    <div class="tr">
      <div class="th">Employee Name</div>
      <div class="th"><%= link_to "Start Date", @organisation, data: { sort: "start", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th"><%= link_to "Start Time", @organisation, data: { sort: "start", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th"><%= link_to "Finish Time", @organisation, data: { sort: "finish", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th"><%= link_to "Break Length (minutes)", @organisation, data: { sort: "break", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th">Hours Worked</div>
      <div class="th">Shift Cost</div>
      <div class="th"></div>
    </div>
    <div style="display:contents;" data-show="current" data-shifts-target="table">
      <%= render "shifts", shifts: @shifts %>
    </div>
    <%= form_for [@organisation, @shift], html: { class: "tr", data: { current: "false", shifts_target: "newForm" } } do |f| %>
      <div class="td"><%= current_user.full_name %></div>
      <div class="td"><%= f.date_field :start_date, form: "new_shift" %></div>
      <div class="td"><%= f.time_field :start_time, form: "new_shift" %></div>
      <div class="td"><%= f.time_field :finish, form: "new_shift" %></div>
      <div class="td"><%= f.number_field :break, step: 1, form: "new_shift" %></div>
      <div class="td"><%= f.submit form: "new_shift", data: { action: "submit->shifts#createShift"} %></div>
      <div class="td"></div>
      <div class="td"></div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="flex--space-between">
  <h1><%= link_to "Adnat", organisations_path, id: "logo" %></h1>
  <% if current_user %>
    <p>Logged in as <%= current_user.full_name %> <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn--red" %></p>
  <% end %>
</nav>

app/views/shifts/_shifts.html.erb
<% shifts.each do |shift| %>
  <% if shift.user.organisation == shift.organisation %>
    <div class="tr" data-current="false" data-rowid="<%= shift.id %>">
  <% else %>
    <div class="tr" style="display:none;" data-current="true" data-rowid="<%= shift.id %>">
  <% end %>
      <div class="td"><%= shift.user.full_name %></div>
      <div class="td"><%= shift.start.strftime("%d/%m/%Y")%></div>
      <div class="td"><%= shift.start.strftime("%H:%M") %></div>
      <div class="td"><%= shift.finish.strftime("%H:%M") %></div>
      <div class="td"><%= shift.break %></div>
      <div class="td"><%= "%.2f" % shift.hours %></div>
      <div class="td">£<%= "%.2f" % ((shift.hours - shift.sunday_hours) * @organisation.hourly_rate + (shift.sunday_hours * @organisation.hourly_rate * 2)) %></div>
  <% if shift.user.organisation == shift.organisation %>
      <div class="td">
        <%= link_to "Edit", shifts_path, data: { id: shift.id, action: "click->shifts#showForm" } %>
        <%= link_to "Delete", shift, method: :delete %>
      </div>
    </div>
    <%= form_for shift, html: { class: "tr", style: "display:none;", data: { formid: shift.id } } do |f| %>
      <div class="td"><%= current_user.full_name %></div>
      <div class="td"><%= f.date_field :start_date, form: "edit_shift_#{shift.id}", value: Date.parse(shift.start.to_s) %></div>
      <div class="td"><%= f.time_field :start_time, form: "edit_shift_#{shift.id}", value: (Time.parse(shift.start.to_s)).strftime("%T.%L") %></div>
      <div class="td"><%= f.time_field :finish, form: "edit_shift_#{shift.id}" %></div>
      <div class="td"><%= f.number_field :break, step: 1, form: "edit_shift_#{shift.id}" %></div>
      <div class="td"><%= f.submit form: "edit_shift_#{shift.id}" %></div>
      <div class="td"></div>
      <div class="td"><%= link_to "Cancel", shifts_path, data: { id: shift.id, action: "click->shifts#hideForm" } %></div>
    <% end %>
  <% else %>
      <div class="td">
      </div>
    </div>
  <% end %>
<% end %>
<%= form_for @shift, html: { class: "tr", data: { current: "false" } } do |f| %>
  <div class="td"><%= current_user.full_name %></div>
  <div class="td"><%= f.date_field :start_date, form: "new_shift" %></div>
  <div class="td"><%= f.time_field :start_time, form: "new_shift" %></div>
  <div class="td"><%= f.time_field :finish, form: "new_shift" %></div>
  <div class="td"><%= f.number_field :break, step: 1, form: "new_shift" %></div>
  <div class="td" colspan="3"><%= f.submit form: "new_shift" %></div>
<% end %>

app/views/shifts/index.html.erb
<h2><%= @organisation.name %></h2>
<h3>Shifts</h3>
<div data-controller="shifts">

  <div>
    <%= link_to "Current Employees", shifts_path, data: { action: "click->shifts#showCurrent" } %>
    <%= link_to "Previous Employees", shifts_path, data: { action: "click->shifts#showPrevious" } %>
  </div>

  <div>
    <p>Filter by date range: </p>
    <%= form_tag shifts_path, method: :get, id: "filter_shift", data: { shifts_target: "form" } do %>
      <%= date_field_tag :start_date, params[:start_date], form: "filter_shift", data: { shifts_target: "startDate" } %>
      <%= date_field_tag :finish_date, params[:finish_date], form: "filter_shift", data: { shifts_target: "finishDate" } %>
      <%= button_tag "Filter Dates", type: "submit", form: "filter_shift", data: { action: "click->shifts#filterDate" } %>
    <% end %>
    <%= button_tag "Clear Date", data: { action: "click->shifts#clearDate" } %>
  </div>

  <div>
    <p>Search for an employee: </p>
    <%= form_tag shifts_path, method: :get, data: { shifts_target: "searchForm" } do %>
      <%= text_field_tag :query, params[:query], placeholder: "Employee name", data: { action: "input->shifts#search", shifts_target: "input" } %>
    <% end %>
  </div>

  <div class="table">
    <div class="tr">
      <div class="th">Employee Name</div>
      <div class="th"><%= link_to "Start Date", shifts_path, data: { sort: "start", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th"><%= link_to "Start Time", shifts_path, data: { sort: "start", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th"><%= link_to "Finish Time", shifts_path, data: { sort: "finish", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th"><%= link_to "Break Length (minutes)", shifts_path, data: { sort: "break", order: "ASC", action: "click->shifts#sortColumn" } %></div>
      <div class="th">Hours Worked</div>
      <div class="th">Shift Cost</div>
      <div class="th"></div>
    </div>
    <div style="display:contents;" data-show="current" data-shifts-target="table">
      <%= render "shifts", shifts: @shifts %>
    </div>
  </div>


</div>